export {default as About} from "./About"
export {default as BookDetails} from "./BookDetails"
export {default as Cart} from "./Cart"
export {default as Home} from "./Home"
export {default as OrderDetails} from "./OrderDetails"
export {default as Profile} from "./Profile"
export {default as Shop} from "./Shop"
